"""add_api_key

Revision ID: 43625c031d25
Revises: 3394ae8e4f3a
Create Date: 2023-04-17 21:51:23.147441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43625c031d25'
down_revision = '3394ae8e4f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'api_key',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'api_key',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
